attributes:
  domain:
    value: 'example.com'
    label: 'LDAP domain'
    description: 'LDAP domain name'
    weight: 20
    type: "text"
    regex:
      source: '^([a-zA-Z0-9._-]+)$'
      error: "Domain should match regex '^([a-zA-Z0-9._-]+)$'"
  url:
    value: 'dc=example,dc=com'
    label: 'LDAP URL'
    description: 'URL for connecting to the LDAP server.'
    weight: 25
    type: "text"
    regex:
      source: '^ldap:\/\/([a-zA-Z0-9._-]+)(:[0-9]+)?$'
      error: "LDAP URL should match regex 'ldap://([a-zA-Z0-9._-]+)(:[0-9]+)?$'"
  suffix:
    value: 'cn=example,cn=com'
    label: 'LDAP Suffix'
    description: 'LDAP server suffix.'
    weight: 26
    type: "text"
  user:
    value: 'cn=admin,dc=local'
    label: 'LDAP User'
    description: 'User BindDN to query the LDAP server.'
    weight: 30
    type: "text"
  password:
    value: 'changeMe'
    label: 'LDAP User Password'
    description: 'Password for the BindDN to query the LDAP server.'
    weight: 35
    type: "password"
    regex:
      source: '^([a-zA-Z0-9_-]+)$'
      error: "Password should match regex '^([a-zA-Z0-9_-]+)$'"
  query_scope:
    value: 'one'
    label: 'LDAP Query Scope'
    description: 'The LDAP scope for queries, this can be either "one" (onelevel/singleLevel) or "sub" (subtree/wholeSubtree).'
    weight: 40
    type: "text"
  user_tree_dn:
    value: 'ou=Users,dc=example,dc=com'
    label: 'Users Tree DN'
    description: 'Search base for users.'
    weight: 45
    type: "text"
  user_filter:
    value: ''
    label: 'User Filter'
    description: 'LDAP search filter for users.'
    weight: 46
    type: "text"
  user_objectclass:
    value: 'inetOrgPerson'
    label: 'User Object Class'
    description: 'LDAP objectclass for users.'
    weight: 50
    type: "text"
  user_id_attribute:
    value: 'cn'
    label: 'User ID Attribute'
    description: 'LDAP attribute mapped to user id.'
    weight: 55
    type: "text"
  user_name_attribute:
    value: 'sn'
    label: 'User Name Attribute'
    description: 'LDAP attribute mapped to user name.'
    weight: 60
    type: "text"
  user_pass_attribute:
    value: 'userPassword'
    label: 'User Password Attribute'
    description: 'LDAP attribute mapped to password.'
    weight: 65
    type: "text"
  user_enabled_attribute:
    value: 'enabled'
    label: 'User Enabled/Disabled Attribute'
    description: 'LDAP attribute mapped to enabled/disabled.'
    weight: 66
    type: "text"
